### ISSUE TITLE
Links in talk notification and link to the newsfeed point to "localhost"

### ISSUE THREAD

**Issue by HaraldJoerg** [domm/ACT-PSGI-demo#9]
The templates templates/talk/notify_accept_body and templates/talk/notify_body, and the index page of the demo conference are using the variable `global.request.base_url`.  If Act is running behind a frontend server (like nginx in the case of the demo server), then this base_url points to localhost.

This issue isn't visible in a typical developer installation but needs to be fixed in Act.

**Comment by domm** [comment]
This has to be fixed by setting the correct proxy headers (`x-forwarded-for` etc)  and using a Middleware like Plack::Middleware::ReverseProxy (and maybe Plack::Middleware::ReverseProxyPath if the apps are mounted on different paths)

**Comment by HaraldJoerg** [comment]
We already have Plack::Middleware::ReverseProxy in place, and it usually does the trick.  For that particular variable, however, the ReverseProxy middleware is running _too late_ in the stack.  Re-ordering the middleware stack does the trick.  I'd also like to write some test for this case.
